/*
 * This source file was generated by the Gradle 'init' task
 */
package prgr;

import java.util.Arrays;
import java.util.Comparator;
import java.util.stream.Collectors;

public class App {

    // random array 1000 values (-500 to 500)

    public int[] randomArray() {

        int[] array = new int[1000];

        for (int i = 0; i < array.length; i++) {
            array[i] = (int) (Math.random() * 1000) - 500;
        }
        return array;
    }

    public void filterOdd(int[] array) {
        int[] filtered = Arrays.stream(array)
                .filter(n -> n % 2 == 0)
                .toArray();
        for (int i = 0; i < filtered.length; i++) {
            filtered[i] *= 2;
        }
        int average = (int) Arrays.stream(filtered).average().orElse(0);
        System.out.println("Average: " + average);
    }

    // declare class Osoba

    public static class Osoba {

        private String name;
        private String surname;
        private int age;
        private String city;
        private int annualIncome;

        public Osoba(String name, String surname, int age, String city, int annualIncome) {
            this.name = name;
            this.surname = surname;
            this.age = age;
            this.city = city;
            this.annualIncome = annualIncome;
        }

        // define generator of Osobas

        public static Osoba[] generate(int numberofpersons) {
            String[] names = { "john", "Jane", "Michael", "Emily", "David", "Sarah", "Robert", "Jessica", "Daniel",
                    "Laura" };
            String[] surnames = { "Smith", "Johnson", "Brown", "Taylor", "Anderson", "Thomas", "Jackson", "White",
                    "Harris", "Martin" };
            String[] cities = { "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia",
                    "San Antonio", "San Diego", "Dallas", "San Jose" };
            Osoba[] osoby = new Osoba[numberofpersons];

            for (int i = 0; i < osoby.length; i++) {

                String name = names[(int) (Math.random() * names.length)];
                String surname = surnames[(int) (Math.random() * surnames.length)];
                int age = (int) (Math.random() * 60) + 10;
                String city = cities[(int) (Math.random() * cities.length)];
                int annualIncome = (int) (Math.random() * 100000) + 20000;

                osoby[i] = new Osoba(name, surname, age, city, annualIncome);
            }
            return osoby;
        }
    }

    // stream 50 osob
    public void streamOsob() {

        final String RESET = "\u001B[0m";
        final String RED = "\u001B[31m";
        final String YELLOW = "\u001B[33m";
        final String BLUE = "\u001B[34m";
        final String GREEN = "\u001B[32m";

        
        Osoba[] osoby = Osoba.generate(50);
        Arrays.sort(osoby, Comparator.comparing(o -> o.name));
        Arrays.stream(osoby).forEach(osoba -> {

            if (Character.isLowerCase(osoba.name.charAt(0))) {
                System.out.println(RED + "Invalid name format: " + osoba.name + RESET);
            } else if (osoba.age < 18) {
                System.out.println(YELLOW + "Underage: " + osoba.name + " " + osoba.surname + ", " + osoba.age + RESET);
            } else if (osoba.annualIncome < 30000 && osoba.age > 18) {
                System.out.println(
                        BLUE + "Low income: " + osoba.name + " " + osoba.surname + ", " + osoba.annualIncome + RESET);
            } else {
                System.out
                        .println(GREEN + osoba.name + " " + osoba.surname + ", " + osoba.age + ", " + osoba.city + ", "
                                + osoba.annualIncome + RESET);
            }
        });

        // number of persons under 18 years with low annual income for each city
        Arrays.stream(osoby)
                .filter(o -> o.age < 18 && o.annualIncome < 30000)
                .collect(Collectors.groupingBy(o -> o.city, Collectors.counting()))
                .forEach((city, count) -> System.out.println(
                        GREEN + "Number of underage persons with low income in " + city + ": " + count + RESET));
    }

    public static void main(String[] args) {

        App app = new App();

        System.out.println("\n");
        System.out.println("----- List of persons -----");
        System.out.println("\n");

        app.streamOsob();
    }
}
